#!/bin/sh

FILTER="sms_in"
FILENAME=/home/fri/fessbox/backend-node/log/debug.log
SUFFIX=`date '+%Y.%m.%d-%H'`

if [ -s $FILENAME-$SUFFIX ];then
  SMS=$(/usr/bin/grep -cF "$FILTER" $FILENAME-$SUFFIX)
  echo $SMS
else 
  echo 0
fi
