#!/bin/sh

FILTER="from ring to master"
FILENAME=/home/fri/fessbox/backend-node/log/debug.log
SUFFIX=`date '+%Y.%m.%d-%H'`
if [ -s $FILENAME-$SUFFIX ]
        then /usr/bin/grep -cF "$FILTER" $FILENAME-$SUFFIX
        else echo 0
fi
