#!/bin/sh

FILTER="sms_in"
FILENAME=/home/fri/fessbox/backend-node/log/debug.log
SUFFIX=`date '+%Y.%m.%d-%H'`
echo $FILENAME-$SUFFIX

if [ -s $FILENAME-$SUFFIX ]
        then /usr/bin/grep -cF "$FILTER" $FILENAME-$SUFFIX
        else echo 0
fi
